version: '3.4'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=abcd.1234
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
